### ISSUE TITLE
Is there a way to take parts needed only, not the entire theme?

### ISSUE THREAD

**Issue by jques17** [DuskWasHere/dusk-obsidian-vault#1]
Hi,

Is there a way to take the parts needed only, not the full theme? For example, I am interested in the hub part only.

**Comment by DuskWasHere** [comment]
Yes you can. All the hub files can function independently.
The homepage is very long. I can maybe make a video for this or better yet the whole vault walkthrough on youtube but will take some time to prepare.

For now maybe try to follow these steps and see if you can replicate:

1. Paste the CSS snippets into your vault:
	- base
	- datacore-classes
	- MCL-multi-column
2. Paste the HUB folder into your vault along with the Hub files
3. Install the `Force note view mode community plugin` and set the view mode for the file and folder to `ObsidianUIMode:preview`
4. Configure the contents of each file

# Configuration Instructions:
## Map of Content
Plugins Needed:
- BRAT (this will be used for the datacore plugin)
	- install and enable datacore with Brat
	- this is the link: https://github.com/blacksmithgu/datacore
Configuration:
- open the Map of Content file and change the view mode to `source view`
	- edit the configuration part of the files:
		- `HUB>Map of Content`
		- `SYSTEM>MOBILE HUB>Mobile Map of Content`
		- when you're editing the configuration part note that the things under `dynamicColumnProperties` are the columns displayed and the note property field it looks into
- DONE!

## Mail Box
Plugins Needed:
- BRAT (this will be used for the datacore plugin)
	- install and enable datacore with Brat
	- this is the link: https://github.com/blacksmithgu/datacore
- js-engine
- templater
Configuration:
- edit your templates (THIS IS OPTIONAL IF YOU HAVE MEETING AND PROJECT NOTES):
	- for meetings: the only important thing to have here is the `meeting_status` field in the property
		- look at `SYSTEM>TEMPLATE>FORMAT>template_meeting_general` for reference
	- for project: the only important thing to have here is the `Status` field in the property
		- look at `SYSTEM>TEMPLATE>FORMAT>template_project for reference
- open the Map of Content file and change the view mode to `source view`
	- edit the configuration part of the files:
		- `HUB>Map of Content`
		- `SYSTEM>MOBILE HUB>Mobile Map of Content`
- go to homepage and edit the view to `source view`
- find the two `js-engine` code blocks
- update the configuration (you only need to update this part) section of the code to your configuration.
-  now go to `STSTEM>TEMPLATE>CODE`
	- update the three scripts
		- toggle_todo: just update this with your configurations
		- toggle_todo_meeting: paste the 2nd `js-engine` code block you updated from homepage in here
		- toggle_todo_revert: paste the 1st `js-engine` code block you updated from homepage in here
- go to templater plugin
	- under template hotkeys add this: `SYSTEM/TEMPLATE/CODE/toggle_todo.md`
	- set a hotkey for it `Ctrl+Space`
- DONE!

NOTE: doing this will allow you to use `Page Task` on any note when you press the hotkey and also display that in your Mail Box.


## Homepage
Plugins needed:
- tabs
- quickadd
- meta-bind
- admonition
- tasks
- dataview
- js-engine
- hotkeys for specific files
- todoist-sync
- BRAT (this will be used for the datacore plugin)
	- install and enable datacore with Brat
	- this is the link: https://github.com/blacksmithgu/datacore
Code configuration
- if you want the `Page Task` feature in your vault:
	- go to homepage and edit the view to `source view`
	- find the two `js-engine` code blocks
	- update the configuration (you only need to update this part) section of the code to your configuration.
	-  now go to `STSTEM>TEMPLATE>CODE`
		- update the three scripts
			- toggle_todo: just update this with your configurations
			- toggle_todo_meeting: paste the 2nd `js-engine` code block you updated from homepage in here
			- toggle_todo_revert: paste the 1st `js-engine` code block you updated from homepage in here
- if you don't want the page task feature in your vault: 
	- go to homepage and edit the view to `source view`
	- find the two js-engine code blocks
	- delete them
- you now want to replicate the `multi-select note type` command from quickadd along with the nested command (this is for the create new note button)
- after that you want to make the homepage buttons work. 
	- `Ctrl+P` then select `meta-bind open button builder` and on actions press `add command` and then find your commands
	
Note: Homepage has a lot of moving parts. Difficult to explain all here but hopefully this helps.
