### ISSUE TITLE
Using Todoist instead of Obsidian Tasks

### ISSUE THREAD

**Issue by immensespace** [DuskWasHere/dusk-obsidian-vault#2]
Hey! Very cool template, been playing around with it, and will probably use it on the long term. Thank you for the work. 

I see in the daily note that tasks seem to be using Obsidian Tasks. How would you recommend switching this to use todoist? 

I see on the homepage that there is todoist sync, I was wondering if instead todoist can replace obsidian tasks so that there aren't project tasks, obsidian tasks, and todoist tasks to check. Seems to simplify enough with just todoist and the project task statuses.

**Comment by DuskWasHere** [comment]
Hello yes, you can replace the Obsidian Tasks in daily notes to todoist ones.
- This documentation link might help you: [todoist](https://jamiebrynes7.github.io/obsidian-todoist-plugin/docs/query-blocks)

Note: I believe you cannot put it inside tabs you you might need to have a workaround for it, an easy way is through the multi-column callouts
